# travis CI config
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - pypy3.5
matrix:
  fast_finish: true

# Use fast travis build infrastructure explicitly
dist: xenial
sudo: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y jackd2 libjack-jackd2-0
  - cat /etc/security/limits.conf
  - ulimit -l
  - echo $USER
  - sudo bash -c "echo '@travis - rtprio 99' >> /etc/security/limits.conf"
  - sudo bash -c "echo '@travis - memlock unlimited' >> /etc/security/limits.conf"
  - ulimit -l unlimited
  - cat /etc/security/limits.conf
install:
  - pip install .
  - pip install -r requirements-dev.txt
script:
  - pytest tests/
  - python -E -Wall -bb -c 'import miniaudio'
